
package Cliente.Frame;

import Cliente.Logica.Administrador;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author <<Alonso Guerrero Alvarado, Valeria Hernandez, Adrian Astua, Carlos Madrigal>>
 */
public class Ventana_Cliente extends javax.swing.JFrame {
    static Administrador adm = new Administrador();
    
    public Ventana_Cliente() {
        initComponents();
        
        setTitle("POKEMON");
       
        setSize(580,520);
        setResizable(false);
        setLocationRelativeTo(null); /*Cambia la ubicación al centro de la pantalla*/
        
        btn_Atacar.setVisible(false);
        Habilidar_Skills(false);
        is_Atacando(false);
        
        lbl_Jugador.setText("");
        lbl_Retador.setText("");
        
        Vida_Jugador.setValue(1000);
        Vida_Retador.setValue(1000);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Atacar = new javax.swing.JButton();
        btn_S2 = new javax.swing.JButton();
        btn_S1 = new javax.swing.JButton();
        btn_S3 = new javax.swing.JButton();
        btn_S4 = new javax.swing.JButton();
        lbl_Estado = new javax.swing.JLabel();
        lbl_Retador = new javax.swing.JLabel();
        lbl_Jugador = new javax.swing.JLabel();
        Vida_Retador = new javax.swing.JProgressBar();
        Vida_Jugador = new javax.swing.JProgressBar();
        Imagen_Jugador = new javax.swing.JLabel();
        Imagen_Retador = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_Atacar.setText("Atacar");
        btn_Atacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtacarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Atacar);
        btn_Atacar.setBounds(30, 360, 130, 30);

        btn_S2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S2);
        btn_S2.setBounds(410, 380, 140, 30);

        btn_S1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S1);
        btn_S1.setBounds(250, 380, 150, 30);

        btn_S3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S3);
        btn_S3.setBounds(250, 420, 150, 30);

        btn_S4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_S4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_S4);
        btn_S4.setBounds(410, 420, 140, 30);

        lbl_Estado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(lbl_Estado);
        lbl_Estado.setBounds(30, 450, 180, 20);

        lbl_Retador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Retador.setText("Retador");
        getContentPane().add(lbl_Retador);
        lbl_Retador.setBounds(10, 10, 180, 20);

        lbl_Jugador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_Jugador.setText("Jugador");
        getContentPane().add(lbl_Jugador);
        lbl_Jugador.setBounds(340, 270, 180, 20);

        Vida_Retador.setForeground(new java.awt.Color(0, 255, 0));
        Vida_Retador.setMaximum(1000);
        getContentPane().add(Vida_Retador);
        Vida_Retador.setBounds(10, 40, 220, 20);

        Vida_Jugador.setForeground(new java.awt.Color(0, 255, 0));
        Vida_Jugador.setMaximum(1000);
        getContentPane().add(Vida_Jugador);
        Vida_Jugador.setBounds(340, 300, 220, 20);
        getContentPane().add(Imagen_Jugador);
        Imagen_Jugador.setBounds(10, 160, 270, 160);
        getContentPane().add(Imagen_Retador);
        Imagen_Retador.setBounds(330, 10, 240, 140);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cliente/Imagenes/bg.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, -20, 580, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtacarActionPerformed
        Habilidar_Skills(true);
    }//GEN-LAST:event_btn_AtacarActionPerformed

    private void btn_S1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S1ActionPerformed
        adm.Atacar(this);
    }//GEN-LAST:event_btn_S1ActionPerformed

    private void btn_S2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S2ActionPerformed
        adm.Atacar(this);
    }//GEN-LAST:event_btn_S2ActionPerformed

    private void btn_S3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S3ActionPerformed
        adm.Atacar(this);
    }//GEN-LAST:event_btn_S3ActionPerformed

    private void btn_S4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_S4ActionPerformed
        adm.Atacar(this);
    }//GEN-LAST:event_btn_S4ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Ventana_Cliente().setVisible(true);
            }
        });
    }
    */
    
   
     // Habilita los botones de ataque al usuario, segun su turno pasando su estado como un boolean
   
    public void is_Atacando(boolean Estado) {
        if (Estado)
            lbl_Estado.setText("Listo para atacar.");
        else
            lbl_Estado.setText("Esperando al oponente.");
    }
    
    private void Habilidar_Skills(boolean Estado)
    {
        btn_S1.setVisible(Estado);
        btn_S2.setVisible(Estado);
        btn_S3.setVisible(Estado);
        btn_S4.setVisible(Estado);
        
        btn_Atacar.setVisible(false);
    }
    
    
    
     
    
    //Crea el cliente de esta forma para poderlo enlazar al servidor
    
    public static void main(String[] args) {
        Ventana_Cliente VC = new Ventana_Cliente();
        adm.Iniciar_Juego(VC);
      
    }

    public JLabel getImagen_Jugador() {
        return Imagen_Jugador;
    }

    public void setImagen_Jugador(JLabel Imagen_Jugador) {
        this.Imagen_Jugador = Imagen_Jugador;
    }

    public JLabel getImagen_Retador() {
        return Imagen_Retador;
    }

    public void setImagen_Retador(JLabel Imagen_Retador) {
        this.Imagen_Retador = Imagen_Retador;
    }

    public JProgressBar getVida_Jugador() {
        return Vida_Jugador;
    }

    public void setVida_Jugador(JProgressBar Vida_Jugador) {
        this.Vida_Jugador = Vida_Jugador;
    }

    public JProgressBar getVida_Retador() {
        return Vida_Retador;
    }

    public void setVida_Retador(JProgressBar Vida_Retador) {
        this.Vida_Retador = Vida_Retador;
    }

    public JLabel getLbl_Jugador() {
        return lbl_Jugador;
    }

    public void setLbl_Jugador(JLabel lbl_Jugador) {
        this.lbl_Jugador = lbl_Jugador;
    }

    public JLabel getLbl_Retador() {
        return lbl_Retador;
    }

    public void setLbl_Retador(JLabel lbl_Retador) {
        this.lbl_Retador = lbl_Retador;
    }

    public JButton getBtn_S1() {
        return btn_S1;
    }

    public void setBtn_S1(JButton btn_S1) {
        this.btn_S1 = btn_S1;
    }

    public JButton getBtn_S2() {
        return btn_S2;
    }

    public void setBtn_S2(JButton btn_S2) {
        this.btn_S2 = btn_S2;
    }

    public JButton getBtn_S3() {
        return btn_S3;
    }

    public void setBtn_S3(JButton btn_S3) {
        this.btn_S3 = btn_S3;
    }

    public JButton getBtn_S4() {
        return btn_S4;
    }

    public void setBtn_S4(JButton btn_S4) {
        this.btn_S4 = btn_S4;
    }

    public JButton getBtn_Atacar() {
        return btn_Atacar;
    }

    public void setBtn_Atacar(JButton btn_Atacar) {
        this.btn_Atacar = btn_Atacar;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Imagen_Jugador;
    private javax.swing.JLabel Imagen_Retador;
    private javax.swing.JProgressBar Vida_Jugador;
    private javax.swing.JProgressBar Vida_Retador;
    private javax.swing.JButton btn_Atacar;
    private javax.swing.JButton btn_S1;
    private javax.swing.JButton btn_S2;
    private javax.swing.JButton btn_S3;
    private javax.swing.JButton btn_S4;
    private javax.swing.JLabel lbl_Estado;
    private javax.swing.JLabel lbl_Jugador;
    private javax.swing.JLabel lbl_Retador;
    // End of variables declaration//GEN-END:variables
}
